name: cdd
description: Discord bot for cdd server
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  nyxx: ^2.0.0-rc.5
  nyxx_commander: ^2.0.0-rc.5
  nyxx_interactions: ^2.0.0-rc.5
dependencies: 
  args: ^2.1.0
